name: deeplabV3
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.01.10
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=23.0.1
  - python=3.8.16
  - readline=8.2
  - setuptools=66.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - altair==4.2.2
      - attrs==23.1.0
      - backports-zoneinfo==0.2.1
      - blinker==1.6.2
      - cachetools==5.3.0
      - certifi==2023.5.7
      - charset-normalizer==3.1.0
      - click==8.1.3
      - decorator==5.1.1
      - entrypoints==0.4
      - filelock==3.12.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - idna==3.4
      - importlib-metadata==6.6.0
      - importlib-resources==5.12.0
      - jinja2==3.1.2
      - jsonschema==4.17.3
      - markdown-it-py==2.2.0
      - markupsafe==2.1.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.24.3
      - opencv-python-headless==4.7.0.72
      - packaging==23.1
      - pandas==2.0.1
      - pillow==9.5.0
      - pkgutil-resolve-name==1.3.10
      - protobuf==3.20.3
      - pyarrow==12.0.0
      - pydeck==0.8.1b0
      - pygments==2.15.1
      - pympler==1.0.1
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - pytz==2023.3
      - requests==2.30.0
      - rich==13.3.5
      - six==1.16.0
      - smmap==5.0.0
      - streamlit==1.22.0
      - streamlit-drawable-canvas==0.9.2
      - sympy==1.12
      - tenacity==8.2.2
      - toml==0.10.2
      - toolz==0.12.0
      - torch==2.0.1+cpu
      - torchvision==0.15.2+cpu
      - tornado==6.3.2
      - typing-extensions==4.5.0
      - tzdata==2023.3
      - tzlocal==5.0.1
      - urllib3==2.0.2
      - validators==0.20.0
      - watchdog==3.0.0
      - zipp==3.15.0
