name: SGenv
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cloudpickle=1.2.2
  - cudatoolkit=11.0.221
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.9.0
  - dbus=1.13.12
  - decorator=4.4.1
  - docopt=0.6.2
  - expat=2.2.6
  - fastrlock=0.5
  - ffmpeg=4.3.1
  - flit-core=3.6.0
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.63.1
  - gmp=6.2.0
  - gnutls=3.6.13
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - imageio=2.6.1
  - intel-openmp=2019.4
  - jpeg=9b
  - kiwisolver=1.1.0
  - lame=3.100
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.3.0
  - libgomp=9.3.0
  - libiconv=1.16
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - libxcb=1.13
  - libxml2=2.9.9
  - matplotlib=3.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.1
  - nettle=3.4.1
  - networkx=2.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.17.4
  - numpy-base=1.17.4
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1t
  - pcre=8.43
  - pillow=6.2.1
  - pip=19.3.1
  - pyparsing=2.4.5
  - pyqt=5.9.2
  - python=3.7.5
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.7.0
  - pytz=2019.3
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - qt=5.9.7
  - readline=7.0
  - scikit-image=0.15.0
  - scipy=1.3.2
  - setuptools=42.0.2
  - sip=4.19.8
  - six=1.13.0
  - sqlite=3.30.1
  - tk=8.6.8
  - toolz=0.10.0
  - torchaudio=0.7.0
  - torchvision=0.8.0
  - tornado=6.0.3
  - typing_extensions=4.4.0
  - wheel=0.33.6
  - x264=1!152.20180806
  - xz=5.2.4
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.3.7
