name: STCGANenv
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - cudatoolkit=11.1.1
  - ffmpeg=4.3
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - intel-openmp=2021.4.0
  - jpeg=9b
  - lame=3.100
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.17
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtiff=4.0.9
  - libuv=1.43.0
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - nettle=3.6
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.21.5
  - numpy-base=1.21.5
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1t
  - pillow=5.4.1
  - pip=22.3.1
  - python=3.7.16
  - pytorch=1.8.0
  - readline=8.2
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.41.2
  - tk=8.6.12
  - torchaudio=0.8.0
  - torchvision=0.9.0
  - typing_extensions=4.5.0
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - cycler==0.11.0
      - fonttools==4.38.0
      - kiwisolver==1.4.4
      - matplotlib==3.5.3
      - packaging==23.1
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - tqdm==4.65.0
