name: SF
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - cudatoolkit=11.1.1
  - ffmpeg=4.3
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.13
  - intel-openmp=2021.4.0
  - jpeg=9b
  - lame=3.100
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.17
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtiff=4.0.9
  - libuv=1.43.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - nettle=3.6
  - ninja=1.11.0
  - numpy-base=1.21.5
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1t
  - pip=22.3.1
  - python=3.7.16
  - python_abi=3.7
  - readline=8.2
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.41.2
  - tk=8.6.12
  - typing_extensions=4.5.0
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - charset-normalizer==3.1.0
      - cycler==0.11.0
      - dataclasses==0.6
      - einops==0.6.1
      - filelock==3.12.0
      - fonttools==4.38.0
      - fsspec==2023.1.0
      - h5py==3.8.0
      - huggingface-hub==0.14.1
      - idna==3.4
      - imageio==2.28.1
      - importlib-metadata==6.6.0
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - linformer==0.2.1
      - matplotlib==3.5.3
      - natsort==8.3.1
      - networkx==2.6.3
      - numpy==1.21.6
      - opencv-python==4.7.0.72
      - packaging==23.1
      - pillow==9.5.0
      - ptflops==0.7
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pywavelets==1.3.0
      - pyyaml==6.0
      - requests==2.30.0
      - safetensors==0.3.1
      - scikit-image==0.19.3
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - threadpoolctl==3.1.0
      - tifffile==2021.11.2
      - timm==0.9.2
      - torch==1.7.1+cu110
      - torchaudio==0.8.0
      - torchvision==0.8.2+cu110
      - tqdm==4.65.0
      - urllib3==2.0.2
      - yacs==0.1.8
      - zipp==3.15.0
